kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: _scss
  style: :compressed

defaults:
  -
    values:
      scope:
        path: "" # the following values apply to all pages
      layout: default
